### ISSUE TITLE
Active a layer to see the movement of pt and bus in Simunto Via

### ISSUE THREAD

**Issue by SarahSie** [matsim-org/matsim-code-examples#399] opened 2020-07-20 13:35 UTC
I have added a layer as Agents/ Vehicles- from Events.
I can see the car movement; however, I cannot see the movement of pt and buses.
How I can see the movement of pt and busses as well?

**Comment by mrieser** [comment] 2020-07-20 18:40
duplicate of #398

**Closed as completed by mrieser** 2020-07-20 18:40 UTC
