### ISSUE TITLE
transit vehicles experiencing unreasonable delays

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-code-examples#421] opened 2020-08-26 19:46 UTC
@mrieser and community members, 
We are getting some unexpected Matsim results where transit vehicles experience unreasonable delays, and would love to get some guidance on how to go about troubleshooting this issue.   
We have been trying to investigate the impact of improved PT services on Oshkosh, Wisconsin, USA using MATSim. Oshkosh is a small city with limited congestion and a modest bus network.  In addition to a base scenario, we are evaluating two scenarios that change the transit schedules, and one that introduces bus-only lanes.  In all scenarios, our intent is to hold the transit Vehicle Revenue Hours (VRH) constant. We expect a noticeable effect on bus ridership, but minimal impact on car trips.  So, for the assessment, we ran the initial base model which justifies as-is condition and along with the adjustment to the transitSchedule.xml, transitVehicles.xml and network.xml  file ran the expected scenario. 
We calculate the transit VRH in two ways: 1) from the transitSchedule file based on the scheduled travel times, and 2) from the output_events.ndjson.gz  file based on the times transit vehicles enter and exit links.  Transit VRH calculated from the events file is much higher than when calculated from the transitSchedule.xml file, by a factor of 2 to 4.5 depending on the scenario. The magnitude of this difference surprised us.  
We suspect that the difference is because transit vehicles are getting stuck in congestion, and when we look at transit arrival and departure events, we see some very large delays (see screenshot below).   
![Screenshot_2020-08-26 Delay - Jupyter Notebook](https://user-images.githubusercontent.com/56562366/91348790-4d949700-e7b2-11ea-9e0e-4d6cf38598ff.png)

You would see from the row 1 of the above screenshot, that the maximum delay occurs at the stopFacility “citycast-gotransit__28408.link:839183098_R “for “veh_66_bus” at 18:51:00 of the simulation. To put it into other words, a 40min PT route journey was now taking 3hrs additional, which seemed totally unreasonable. Other links in the screenshot also are facing similar delays at different times. Given the size of the city and the amount of traffic volume, I think one should be able to drive to the next state in less time than that.
So I mapped the stopFacility to the linkrefId in VIA to analyze the traffic flow. The traffic flow at the link seems pretty reasonable perhaps less than or around 500 for the link capacity of 1800 veh.    
![link_volumes](https://user-images.githubusercontent.com/56562366/91349067-c4319480-e7b2-11ea-9b6c-f148c81dcb05.png)
Similar is the story, if we go upstream in the network from where the link draws traffic input. Route time diagram for the PT route which ply on the link also suggest that the delay in the simulation seems unreasonable. 
![Route-time Diag](https://user-images.githubusercontent.com/56562366/91349111-d3b0dd80-e7b2-11ea-876c-2c62381eb793.png)

We have two guesses here: 
1.	There is a bottleneck in the network somewhere where too much traffic or a network coding error is causing an unreasonable amount of for all vehicles delay. 
2.	We have a configuration.xml setting wrong that is causing an unreasonable delay that is specific to transit vehicles.  

**Our question is:** What steps might we take in diagnosing this?  Are there specific maps we should in Via, or possible settings to check?  We would appreciate any guidance on what to look into next.  

Thank you. 
Vedant

@gregerhardt
@josiekre

**Comment by josiekre** [comment] 2020-08-27 12:43
@vsgo222 Can you look at capacity throughout the day for link 92700128_R (similar plot to the above you made for 839183098_R)? From the route-time diagram, that is the link where all delay starts. If there's not a delay on this particular link, also check the links traversed between that particular stop (citycast-gotransit__766416) and the subsequent one (citycast-gotransit__766417). 

It makes sense that the "largest" delay recorded is at stop 28408 (link 839183098_R) from the route-time diagram. But it also makes sense that there is not an obvious capacity issue on this link because looking at the route-time diagram, the delay does not increase after this stop. So the issue is stemming from something between stops 766416 and 28408 (see route-time diagram).

**Comment by vsgo222** [comment] 2020-08-28 02:39
> 
> 
> @vsgo222 Can you look at capacity throughout the day for link 92700128_R (similar plot to the above you made for 839183098_R)? From the route-time diagram, that is the link where all delay starts. If there's not a delay on this particular link, also check the links traversed between that particular stop (citycast-gotransit__766416) and the subsequent one (citycast-gotransit__766417).
> 
> It makes sense that the "largest" delay recorded is at stop 28408 (link 839183098_R) from the route-time diagram. But it also makes sense that there is not an obvious capacity issue on this link because looking at the route-time diagram, the delay does not increase after this stop. So the issue is stemming from something between stops 766416 and 28408 (see route-time diagram).

Thank you @josiekre. 
I looked at it and did not find anything abnormal both on the capacity and traffic volumes for both upstream or downstream links. However, when I was tracking the PT vehicle (tracking from start to end), I find that the travel time at the following links is the likely reason of the delay:

- 1220715967_F – 60 min
- 1187614728_F – 25 min
- 1187177581_F – 15 min
- 1220828847_F – 15 min
- 838254376 - 80 min

These five links together cause 195min of delay per PT Trip which seems to too high given that the traverse road length on these links amount to 161m. Each of these segment is a single lane type with free speed = 13 kmph and capacity = 900. Except for link = 838254376 which is a two lane road and has capacity = 1800. 
In this case, what should be the appropriate thing to do? Your advise would be very helpful. 

Thank you
Vedant

**Comment by mrieser** [comment] 2020-08-28 12:30
What sample size do you simulate?
How many transit lines run along the mentioned links? And how often do services run on these lines? (--> how many buses should run along this link within 1 hour?)

I've seen cases in the past where a high number of bus lines go along a single link. When the link's capacity is scaled down to, i.e. 10%, but still all 100% of transit runs, this can lead to traffic jams. (otoh, I think citycast scales down the transit vehicles to take the sample size into account)

By default, transit vehicles are larger than regular cars and thus take up more capacity on the links. So if you would have only transit vehicles running along a link, you likely wouldn't observe the full capacity of that link as in the QSim, each transit vehicle counts for multiple vehicles capacity-wise. The link volumes analysis might be a bit misleading in this case, as it suggests additional capacity available, where the actually isn't.

**Comment by vsgo222** [comment] 2020-08-28 15:54
> What sample size do you simulate?
> How many transit lines run along the mentioned links? And how often do services run on these lines? (--> how many buses should run along this link within 1 hour?)

It has 1 bus running every 30min. In other words, 2 bus in 1 hour for 12 hours starting 6:15am until 6:15pm. 

> I've seen cases in the past where a high number of bus lines go along a single link. When the link's capacity is scaled down to, i.e. 10%, but still all 100% of transit runs, this can lead to traffic jams. (otoh, I think citycast scales down the transit vehicles to take the sample size into account)

given the small size of Oshkosh city, we are using 100%. So neither the links capacity nor PT schedule is scaled down. 

> By default, transit vehicles are larger than regular cars and thus take up more capacity on the links. So if you would have only transit vehicles running along a link, you likely wouldn't observe the full capacity of that link as in the QSim, each transit vehicle counts for multiple vehicles capacity-wise. The link volumes analysis might be a bit misleading in this case, as it suggests additional capacity available, where the actually isn't

Actually, the links have (absolute) traffic flow not amounting to more than 1/3rd of the capacity. Connecting links (both upstream and downstream) also have absolute traffic less than 1/3rd of link capacity and the  buses travel at free speed on them.

**Comment by josiekre** [comment] 2020-08-31 07:31
13 kmph is quite slow (~8mph). Can you screenshot the links coloring by free speed so I can see what kind of roads these are? There may be a problem in the underlying map/speed data.

**Comment by vsgo222** [comment] 2020-08-31 22:21
> 
> 
> 13 kmph is quite slow (~8mph). Can you screenshot the links coloring by free speed so I can see what kind of roads these are? There may be a problem in the underlying map/speed data.

@josiekre,
Please find the screenshots of the traversed path. Here the links are classified based on free speed. Links which have brownish yellow color are the actual path traversed by PT "citycast-gotransit__958__0"

![Free speed classification](https://user-images.githubusercontent.com/56562366/91774283-75229f80-ebb6-11ea-88f4-6330552f5731.png)
![ 1 - Screenshot_1](https://user-images.githubusercontent.com/56562366/91774289-7784f980-ebb6-11ea-8715-f82e15c4d075.png)
![2 - 111848689_R to 1220718524_R](https://user-images.githubusercontent.com/56562366/91774293-79e75380-ebb6-11ea-9a1b-ac46abfae5da.png)
![3 - 92696643_F to 1220830291_F](https://user-images.githubusercontent.com/56562366/91774299-7c49ad80-ebb6-11ea-8ba2-e2f98f8c14ac.png)
![4 - 1220830292_F to 92696651_F](https://user-images.githubusercontent.com/56562366/91774302-7e137100-ebb6-11ea-8e75-f126019ba8b3.png)
![5 - 92696652_F to 839183100_F](https://user-images.githubusercontent.com/56562366/91774307-7fdd3480-ebb6-11ea-8cab-51fd5a932254.png)
![6 - 839183100_F to 839183099_R](https://user-images.githubusercontent.com/56562366/91774309-81a6f800-ebb6-11ea-877f-d20c766e9bb8.png)
![7 - 839183099_R to 92696209_R](https://user-images.githubusercontent.com/56562366/91774311-8370bb80-ebb6-11ea-801e-8fa136eee643.png)

**Comment by gregerhardt** [comment] 2020-09-01 15:41
Here is an example of one problem link.  In this particular example, we see a 25 m link, with a capacity of 900 vph, and a free flow speed of 13.41 km/hr.  Looking at the calculated values at the bottom, the average speed is 0.349 km per hour.  So it should take a vehicle 4.29 minutes to traverse this link.  That itself seems unreasonably slow, but still is much less than the numbers reported above.  A couple of things to look at:

1) Can you provide an equivalent screenshot for link 1220715967_F where it takes ~60 min to traverse? 

2) Can you manually calculate the   last four values of the link attributes: Volumes (absolute), Volumes (relative), Avg. Speeds (absolute) and Avg. Speeds (relative)?  You can put it in a spreadsheet, or just show it, allowing us to verify why the speed is so slow.  

3) Related to 2, I don't know Matsim well enough to know what kind of traffic delay function it is using. So part of this task will be to find what that is and for us to learn what can go wrong with that.  So if there is something specific I should be reading, I can start there.  

Thanks! 

![1220716272_F_Screenshot](https://user-images.githubusercontent.com/5774986/91872951-7c918980-ec46-11ea-84a4-a2b356c0efef.png)

**Comment by mrieser** [comment] 2020-09-02 14:23
> a free flow speed of 13.41 km/hr. Looking at the calculated values at the bottom, the average speed is 0.349 km per hour. So it should take a vehicle 4.29 minutes to traverse this link.

By default, MATSim uses meters per second, not km/hr. 13.41m/s equals 48.27km/h, or about 30 miles per hours, which sounds more reasonable. But then, if it is 25.0 meters long, it will take the vehicle in MATSim 2 seconds, and due to node processing in MATSim, one additional second, so 3 seconds in total.

> Related to 2, I don't know Matsim well enough to know what kind of traffic delay function it is using

None. Delays appear when the upstream link is full (storage capacity) and vehicles cannot enter the next link.

**Comment by josiekre** [comment] 2020-09-03 12:19
A free flow speed of 30 miles per hour makes sense for this transit route. The route is traversing local streets downtown Oshkosh. See the attached screenshot.

![Screen Shot 2020-09-03 at 2 14 52 PM](https://user-images.githubusercontent.com/5776153/92113601-68639e80-eda4-11ea-8328-3a7840222ce4.png)

I'm not familiar with the Simunto interface so I don't know how speeds are computed and shown. @mrieser is looking into it... thanks.

**Comment by josiekre** [comment] 2020-11-24 19:04
I think this can be closed as I think we were able to resolve it.

**Closed as completed** 2020-11-24 19:16 UTC
