### ISSUE TITLE
error in EV module

### ISSUE THREAD

**Issue by xy2017** [matsim-org/matsim-code-examples#236] opened 2019-11-05 19:22 UTC
I want to simulate the behavior of  electric vehicles in Matsim, and there is a module named "ev" in file "config.xml". (see below)
`<module name="ev">
        <param name="auxDischargeTimeStep" value="10"/>
        <param name="chargeTimeStep" value="5"/>
        <param name="chargersFile" value="chargers.xml"/>
        <param name="timeProfiles" value="true"/>
        <param name="vehiclesFile" value="evehicles.xml"/>
    </module>`
But the simulation ended with an error: "java.lang.RuntimeException: Unmaterialized config group: ev". So how can I add the "ev" module correctly?
In addition, where can I found the ev's parameter available? I have checked the user documentation, but there's no parameters list about ev.

**Comment by Thomas960707** [comment] 2019-11-05 19:25
Here is the unshown codes:
<config>
    <module name="ev">
        <param name="auxDischargeTimeStep" value="10"/>
        <param name="chargeTimeStep" value="5"/>
        <param name="chargersFile" value="chargers.xml"/>
        <param name="timeProfiles" value="true"/>
        <param name="vehiclesFile" value="evehicles.xml"/>
    </module>

**Comment by Thomas960707** [comment] 2019-11-05 19:25
> <config>
    <module name="ev">
        <param name="auxDischargeTimeStep" value="10"/>
        <param name="chargeTimeStep" value="5"/>
        <param name="chargersFile" value="chargers.xml"/>
        <param name="timeProfiles" value="true"/>
        <param name="vehiclesFile" value="evehicles.xml"/>
    </module>

**Comment by michalmac** [comment] 2019-11-05 20:51
Looks like a duplicate of #235 ??

**Comment by xy2017** [comment] 2019-11-06 15:35
> Looks like a duplicate of #235 ??

**Closed as completed** 2019-12-18 08:55 UTC
